source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Cirrus' do
platform :ios, '9.0'

pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON'
pod 'Mercury'
pod 'DGElasticPullToRefresh'
pod 'FloatingActionSheetController'
pod 'SwiftLocation'

end

